version: 2
mergeable:
  - when: pull_request.*
    validate:
      #exclude PR that starts with 'WIP'
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      #exclude those with label 'WIP'
      - do: label
        must_exclude:
          regex: 'WIP'