version: 2
mergeable:
  - when: pull_request.*
    validate:
      #exclude PR that starts with 'WIP'
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      #exclude those with label 'WIP'
      - do: label
        must_exclude:
          regex: 'WIP'
          
      - do: description
        no_empty:
          enabled: true
          message: Description should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.

  - when: issues.opened
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description should not be empty. Provide detail with **what** the issue is about.
    fail:
      - do: comment
        payload:
          body: >
            The following problem was found with this issue:
              - It has empty description.

