version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: boardly
  api:
    restart: always
    build: 
      context: .
      dockerfile: src/backend/Dockerfile
    volumes:
      - .env:/.env
    ports:
      - 8080:8080
    depends_on:
      - db
  web:
    restart: always
    build: 
      context: .
      dockerfile: src/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api