package logger

import (
	"log"
	"os"
)

func configLogger() {
	// first initialize the logger

	//  If the file doesn't exist, create it or append to the file
	file, err := os.OpenFile("logs.txt", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		log.Fatal(err)
	}

	// custom loggers:
	//	 out: Any type that implements the io.Writer interface, which is where the log data will be written to
	//	 prefix: A string that is appended to the beginning of each log line
	//	 flag: A set of constants that allow us to define which logging properties to include in each log entry generated by the logger (more on this in the next section)

	InfoLogger := log.New(file, "INFO: ", log.Ldate|log.Ltime|log.Lshortfile)
	WarningLogger := log.New(file, "WARNING: ", log.Ldate|log.Ltime|log.Lshortfile)
	ErrorLogger := log.New(file, "ERROR: ", log.Ldate|log.Ltime|log.Lshortfile)

	log.SetOutput(file)
}
