name: Test

on: 
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  # This is for linting the go files
  lint:
    name: Lint
    strategy:
      matrix:
        os: 
          - macos
          - ubuntu 
          - windows 
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: golangci/golangci-lint-action@v2.5.1

  test:
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
        os: 
          - macos
          - ubuntu 
          - windows
        goarch:
          - 386
          - amd64
        exclude:
          - os: macos
            goarch: 386
    name: test (${{ matrix.os }}/go-${{ matrix.go-version }}/${{ matrix.goarch }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...