name: Test

on: 
  pull_request:
    branches:
      - master

jobs:
  goTest:
    strategy:
      matrix:
        go-version:
          - 1.15
        os: 
          - ubuntu 
        goarch:
          - amd64
    name: test (${{ matrix.os }}/go-${{ matrix.go-version }}/${{ matrix.goarch }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        stable: false
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build the docker-compose stack
      run: docker-compose --env-file .test.env up -d
    - name: Check running containers
      run: docker ps -a
    - name: Test and Coverage
      run: TEST_DIR=$(pwd) go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      env:
          GOARCH: ${{ matrix.goarch }}
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: golangci/golangci-lint-action@v2.5.1


  nextBuild:
    strategy:
      matrix:
        node-version:
          - 12.x
        os: 
          - ubuntu 
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Build the docker-compose stack
      run: docker-compose --env-file .test.env up -d
    - name: Check running containers
      run: docker ps -a
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
