
# name: Vulnerability Scan

# on:
#   pull_request:
#     branches: [ master ]

# jobs:
#   security:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@master
#     - name: Run Snyk to check for vulnerabilities(Web)
#       uses: snyk/actions/node@master
#       continue-on-error: true # To make sure that SARIF upload gets called
#       env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#       with:
#         args: --sarif-file-output=snyk.sarif
        
#     - name: Run Snyk to check for vulnerabilities(Backend)
#       uses: snyk/actions/golang@master
#       continue-on-error: true # To make sure that SARIF upload gets called
#       env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#       with:
#         args: --sarif-file-output=snyk.sarif
        
#     - name: Upload result to GitHub Code Scanning
#       uses: github/codeql-action/upload-sarif@v1
#       with:
#           sarif_file: snyk.sarif
          
          
          

name: Vulnerability Scanning

on:
  pull_request:
    branches: [ master ]

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Trivy vulnerability scanner in fs mode
        uses: anandg112/trivy-action@feat/add-skip-dirs-option
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-fs.sarif'
          severity: 'CRITICAL'
          skip-dirs: "ignored-dir"
          
      - name: DEBUG Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'debug-trivy-results.sarif'
 
          
    
